<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * HabitanteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EntidadRepository extends EntityRepository
{

    /**
    * @return Array
    */
    public function findAllActive($criteria = null)
    {
	$criteria = array_merge(['fechaBaja' => '' ],$criteria);
	$result = $this->findBy($criteria);
        return $result;
    }
}
