<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * TipoViaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TipoViaRepository extends EntityRepository
{

    /**
    * @return QueryBuilder
    */
    public function findAllLikeQueryBuilder( $criteriaLike = null )
    {
        $qb = $this->createQueryBuilder('e');
        
        if ( $criteriaLike ) {
            foreach ( $criteriaLike as $eremua => $filtroa ) {
                $qb->andWhere('e.'.$eremua.' LIKE :'.$eremua)
                    ->setParameter($eremua, '%'.$filtroa.'%');
            }
        }
//	$qb->orderBy('e.noizInformatua', 'DESC');
        return $qb;
    }
}
